#!/bin/bash

if [ ! -f /etc/ssh/sshd_config ]; then
    # Regenerate ssh key per container
    dpkg-reconfigure openssh-server
fi

chown nexus /nexus

# Cleanly kill supervisor when container is stopped
trap 'kill $(jobs -p)' EXIT

# start services
supervisord
